#pragma once

#include "vkc/resource/buffer.hpp"
#include "vkc/resource/image.hpp"
#include "vkc/resource/image_view.hpp"
#include "vkc/resource/memory.hpp"
#include "vkc/resource/present_image.hpp"
#include "vkc/resource/push_constant.hpp"
#include "vkc/resource/sampled_image.hpp"
#include "vkc/resource/sampler.hpp"
#include "vkc/resource/spec_constant.hpp"
#include "vkc/resource/staging_buffer.hpp"
#include "vkc/resource/storage_buffer.hpp"
#include "vkc/resource/storage_image.hpp"
#include "vkc/resource/uniform_buffer.hpp"
